[package]
name = "psila-service"
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
edition = "2018"

[dependencies]
bbqueue = "0.5"
ieee802154 = "0.3"
psila-crypto = { path = "../psila-crypto" }
psila-data = { path = "../psila-data" }
heapless = "0.7"
defmt = "0.3"

[features]
default = []
core = ["psila-data/core"]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
