[package]
name = "psila-service"
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
edition = "2018"

[dependencies]
ieee802154 = { git = "https://github.com/braun-embedded/rust-ieee802.15.4.git", branch = "master" }
bbqueue = { git = "https://github.com/jamesmunns/bbqueue" }
psila-crypto = { path = "../psila-crypto" }
psila-data = { path = "../psila-data" }

[dev-dependencies]
psila-crypto-gcrypt = { path = "../psila-crypto-gcrypt" }
gcrypt = { version = "0.6" }

[features]
default = []
core = ["psila-data/core"]
