[package]
name = "psila-service"
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
bbqueue = "0.4"
ieee802154 = "0.3"
psila-crypto = { path = "../psila-crypto" }
psila-data = { path = "../psila-data" }
heapless = { version = "0.5" }

[dev-dependencies]
psila-crypto-openssl = { path = "../psila-crypto-openssl" }

[features]
default = []
core = ["psila-data/core"]
