[package]
name = "psila-service"
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
bbqueue = "0.4"
ieee802154 = { git = "https://github.com/braun-embedded/rust-ieee802.15.4.git", branch = "master" }
psila-crypto = { path = "../psila-crypto" }
psila-data = { path = "../psila-data" }

[dev-dependencies]
psila-crypto-openssl = { path = "../psila-crypto-openssl" }

[features]
default = []
core = ["psila-data/core"]
