[package]
name = "psila-data"
description = "Library for reading/writing Zigbee packages."
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/blueluna/psilas"
categories = ["network-programming"]
keywords = ["zigbee", "iot", "wpan", "network"]

[features]
default = ["std"]
core = ["heapless"]
std = ["gcrypt"]

[dependencies]
byteorder = { version = "1", default-features = false }
bitflags = "1.0"
gcrypt = { version = "0.6", optional = true }
heapless = { version = "0.5", optional = true }