name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install libgcrypt-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
